### ISSUE TITLE
Broken DrivetrainSubsystem

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#1]
Broken in kinematics after import to VS Code 2022

**Comment by Fruggg** [comment]
Think I got it sorted out. I noted it in the code itself, but the method for normalizing swerve wheels is strange. I'll leave it to someone more in the loop than myself to actually close the issue.

**Comment by JediScoy** [comment]
Looks good! We can try it on a robot Tuesday but the code isn't "angry" anymore and seems to follow something I saw in C.D.
