### ISSUE TITLE
Fix Navx code references

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#18]

**Comment by cdmarshall25** [comment]
I have a successful build now. 

I had to install an update to the “KauaiLabs_navX_FRC” vendor library in VS code. After updating the vendor library, the code built successfully. 

Here's the walkthrough guide for reference. We will have to update this on all the programming laptops.

Scroll down to "Configuring your VSCode Project to use the navX_FRC Library for RoboRIO" and click the link highlighted on the words "latest build". This will download a .zip you'll have to extract, and then run the setup file inside. 

After installing that, follow the instructions listed on the guide to update your vendor library and try out a build!

https://pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/java/

**Comment by cdmarshall25** [comment]
Disregard previous instructions.  I pushed my code updates up to the main branch, and the vendor library update got uploaded with it. Just pull down the updated code to your laptops
