### ISSUE TITLE
Update Navx firmware

### ISSUE THREAD

**Issue by coyotepod** [CyberCoyotes/2022-RapidReact#20]
I have the Navx software on my laptop (Wednesday night)

**Comment by JediScoy** [comment]
[Navx update instructions]](https://www.kauailabs.com/support/navx-mxp/kb/faq.php?id=48)
Need a micro-USB to connect directly to the Nav-x (makes sense); NOT via Rio like I was attempting Thursday night

**Comment by JediScoy** [comment]
Updated from Version 3.0.331 to 3.1.413 on Taz. Need to check on 2022 bot. It takes a bit of searching to locate the .hex file but if you follow the instructions its fine.

[Installing User Home Directory]\navx-mxp\firmware

**Comment by JediScoy** [comment]
Update:  1/7/2022 – Version 4.0.442 is now available – which is compatible with the FRC 2022 Release Candidate 1.  Both offline and online installation methods are supported for installing the library update within VSCode.
