### ISSUE TITLE
Reimage the roboRio from Falcon to 2022

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#31]
Failed to update firmware from Jackson's laptop and Scoy's laptop. After multiple attempts from both machines we are shelving this for now. I'm convinced this it the roboRIO we want to use anyway do to the amount of aluminum dust on it

**Comment by cdmarshall25** [comment]
This is complete. Formatted the Rio like normal using and it worked today. Updated firmware as well.
