### ISSUE TITLE
Lift Command Thumbsticks

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#64]
/** FIXME this did not work, no movement 
    // Use left stick up and down to manually move ONLY left climbing arm up and down
    leftLiftMotor.setDefaultCommand(new DefaultDriveCommand

RobotContainer line 240 ish

**Comment by JediScoy** [comment]
This might still be good to have in a jam, but Cole, current operator, is actually been using the manual lift and pull bumper actions pretty effectively. Effectively. They haven't got them out of sync except one time and they were still able to make the climb

**Comment by coyotepod** [comment]
This might still be good to have in a jam, but Cole, current operator, is actually been using the manual lift and pull bumper actions pretty effectively. Effectively. They haven't got them out of sync except one time and they were still able to make the climb

**Comment by JediScoy** [comment]
We didn't get this figured out this season but so far has been unnecessary so I'm going to close it
