### ISSUE TITLE
Analyze the REV PDH

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#67]
Try to figure out why we have sticky faults so frequent.

**Comment by JediScoy** [comment]
Rev. Hardware client was updated yesterday and is supposed to have more detailed logs for FRC teams

**Comment by coyotepod** [comment]
Rev. Hardware client was updated yesterday and is supposed to have more detailed logs for FRC teams

**Comment by JediScoy** [comment]
There were spikes in the channel outputs for different motors, but the channels -- and thus motors -- were inconsistent. Likely NOT something electrical as this behavior was also observed on the practice bot TAZ. Likely a code issue
