### ISSUE TITLE
Clean up the git branches

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#75]
Remove branches that are no longer in use

**Comment by JediScoy** [comment]
If there is something you want to keep for development down the road, that's cool but maybe its best to fork and move out of this repository? Seems like this one has gotten very cluttered with extra dev branches -- a lot of them were mine :-P

**Comment by cdmarshall25** [comment]
My branches have been hacked off.

**Comment by Fruggg** [comment]
I have cut down my branches
