### ISSUE TITLE
Autonomous Documentation

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#8]
Create a more complex string of auton commands
- [ ] Make one subsystem do more than one command (sequence based)
- [ ] Use different inputs or conditionals (time, distance, sensor data)
- [ ] Run more than one command simultaneously

**Comment by JediScoy** [comment]
This will obviously be broken into specific tasks in the future but this is a skill to start on now

**Comment by JediScoy** [comment]
Chief Delphi profile [SeanSun6814](https://www.chiefdelphi.com/u/seansun6814/activity/portfolio)

**Comment by JediScoy** [comment]
[A Video Walkthrough of Model Based Validation of Autonomous in FRC](https://docs.wpilib.org/en/latest/docs/software/advanced-controls/video-walkthrough.html)
I'm only a few minutes into it and not sure if it'll help me code the stuff, lol, but it is helping me with some of the verbage out there; e.g. pose, odometry. Supposedly the gist of the video is its going to show programmer's how to program the robots and test out logic in virtual/sim so you could do it before the robot is built. I'm not sure if that's possible with swerve however,

**Comment by cdmarshall25** [comment]
Simple auton code example in Java using command based. This is the example I am following for my test auton branch.

First 15 minutes are setting up a drive system for Tele-Op, which we have down already. Still good to watch though, to verify we have all that stuff

Auton drive coding starts at 16 minutes. 

https://www.youtube.com/watch?v=0Xi9yb1IMyA

**Comment by JediScoy** [comment]
I watched his (SeanSun6814) over Christmas break. I need to go back through it.

**Comment by cdmarshall25** [comment]
Closing, keeping for reference.
