### ISSUE TITLE
Auton adjustment

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#85]
Auton from Connor works great -- except the wheel turn 90 degrees perfectly and drive "forward" for the wait time value

**Comment by Minisolarclown** [comment]
So are you saying it's moving side-to-side rather than forwards-backwards?

**Comment by JediScoy** [comment]
Yes, its perfectly straight ... strafing to the left :)

**Comment by JediScoy** [comment]
Also tested today and 4 seconds = 102 inches at 0.70 percent output, so 1 second = 25 inches of "forward" movement in auton

**Comment by Minisolarclown** [comment]
Perfect, that means we have the X speed and Y speed in the Drive2Seconds auton swapped. I'll make the change with a comment in the Drive2Seconds file to correct it.

**Comment by JediScoy** [comment]
Cool "CG_1BallDriveStraight" is the timed based auton

**Comment by Minisolarclown** [comment]
I fixed the issue in Drive2Seconds for your reference and added comments in CG_1BallDriveStraight so you can try and fix that on your own (Lines 58-60 in CG_1BallDriveStraight).
