### ISSUE TITLE
Limelight is stuck in the launch wheel loop

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#92]
See launch automatic code block 27 to 46

**Comment by JediScoy** [comment]
Can't recall if we got this fixed or not but this would be important before moving on to the other limelight based issues

**Comment by JediScoy** [comment]
@cdmarshall25 Did we get this fixed? I think yes??

**Comment by cdmarshall25** [comment]
Nope, the sequence never stops still when you release the button. Commented it out for the comp. 

we dont see any speed changes when moving the reflective target around.

**Comment by JediScoy** [comment]
Closing for now as we are unlikely to use it this year
